Path 👉 to Repo

diff --git a/.github/workflows/GitAction.yml b/.github/workflows/GitAction.yml
--- a/.github/workflows/GitAction.yml
+++ b/.github/workflows/GitAction.yml
@@ -38,10 +38,12 @@ jobs:
       - name: Verify Code Style with Spotless
         run: |
           mvn spotless:check || echo "Spotless check failed. Proceeding with the build."
+          
       - name: Apply Code Style if Needed
         if: failure()
         run: |
           mvn spotless:apply || echo "Spotless apply failed. Proceeding with the build."
+          
       - name: Commit and Push Spotless Changes
         if: failure()
         run: |
@@ -50,21 +52,23 @@ jobs:
           git add .
           git commit -m "Apply Spotless formatting"
           git push
+          
       - name: Run All Tests (Ignore Failures)
         run: |
-          mvn test -DtestFailureIgnore=true || echo "Tests failed but proceeding with the build."
+          mvn -f repo/pom.xml test -DtestFailureIgnore=true || echo "Tests failed but proceeding with the build."
+      
       - name: Run Clean, Package, Install
         run: |
-          mvn clean package install -B
-          cp target/original-uml-editor-shaded.jar target/uml-editor.jar
+          mvn -f repo/pom.xml clean package install -B
+          cp repo/target/original-uml-editor-shaded.jar repo/target/uml-editor.jar
         shell: pwsh
 
       - name: Upload Build Artifacts
         uses: actions/upload-artifact@v4
         with:
           name: build-artifacts-${{ matrix.os }}-${{ matrix.java-version }}
-          path: target/*.jar
-
+          path: repo/target/*.jar
+          
       - name: Determine Release Type
         id: determine_release
         shell: bash
